services:
  postgres:
    image: postgres:15-alpine
    container_name: ntb-database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ntb-network
    restart: always
    env_file: .env

  ntb-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ntb-proxy-server
    ports:
      - "127.0.0.1:8080:8080"
      - "8000:8000"
      - "9000:9000"
    depends_on:
      - postgres
    networks:
      - ntb-network
    restart: always
    env_file: .env

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html:ro
      - /etc/letsencrypt:/etc/nginx/ssl:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - ntb-server
    networks:
      - ntb-network
    restart: always

volumes:
  postgres_data:

networks:
  ntb-network:
    driver: bridge
