services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443" # Теперь снаружи точно 443 порт
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html:ro
      - /etc/letsencrypt:/etc/nginx/ssl:ro
    restart: always