"""Initial migration

Revision ID: 3e4730089f07
Revises: 
Create Date: 2026-06-29 05:39:35.139531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e4730089f07'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_users',
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('api_key', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('tg_id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('tg_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telegram_users')
    # ### end Alembic commands ###
