"""add max_tunnels to telegram_users

Revision ID: 43c6f5a4c1a8
Revises: 3e4730089f07
Create Date: 2026-07-04 17:04:52.863017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43c6f5a4c1a8'
down_revision: Union[str, Sequence[str], None] = '3e4730089f07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_users', sa.Column('max_tunnels', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_users', 'max_tunnels')
    # ### end Alembic commands ###
